esphome:
  name: esphome-directwifi-status
  friendly_name: DirectWifi-Update-Status
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp8266:
  board: esp01_1m

logger:
  level: VERY_VERBOSE
  
api:

ota:
  - platform: esphome
  - platform: web_server

wifi:
  #ssid: !secret wifi_ssid
  #password: !secret wifi_password
  networks:
  #- ssid: !secret wifi_ssid
  #  password: !secret wifi_password
  #  priority: 0.0
  #- ssid: !secret wifi2_ssid
  #  password: !secret wifi2_password
  #  priority: 1.0
  - ssid: !secret wifi3_ssid
    password: !secret wifi3_password
  #  priority: 2.0

  ap:
    ssid: "EspHome-DirectWifi"
    password: "12345678"

web_server:
  port: 80
  version: 3

http_request:
  useragent: esphome_device
  timeout: 60s
  verify_ssl: false

globals:
  - id: internet_ok
    type: bool
    restore_value: true
    initial_value: 'true'

  - id: fail_counter
    type: int
    restore_value: no
    initial_value: '0'

binary_sensor:
  - platform: template
    name: "Internet Status"
    id: internet_status
    device_class: connectivity
    lambda: |-
      return id(internet_ok);
      
sensor:
  - platform: template
    name: "Fail Counter"
    id: internet_fail_counter
    unit_of_measurement: "x"
    accuracy_decimals: 0
    update_interval: 29s
    lambda: |-
      return id(fail_counter);

interval:
  - interval: 60s
    then:
      - http_request.get:
          url: http://neverssl.com
          max_response_buffer_size: 256
          capture_response: false
          on_response:
            then:
              - lambda: |-
                  if (response->status_code == 200) {
                    id(fail_counter) = 0;   // reset contador em caso de sucesso
                    id(internet_ok) = true;
                  } else {
                    id(fail_counter) += 1;
                    if (id(fail_counter) >= 10) {
                      id(internet_ok) = false;
                    }
                  }
          on_error:
            then:
              - lambda: |-
                  id(fail_counter) += 1;
                  if (id(fail_counter) >= 10) {
                    id(internet_ok) = false;
                  }