esphome:
  name: esphome-loviz-status
  friendly_name: Loviz-Status
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp8266:
  board: esp01_1m

logger:
  level: VERY_VERBOSE
  
api:

ota:
  - platform: esphome
  - platform: web_server

wifi:
  #ssid: !secret wifi_ssid
  #password: !secret wifi_password
  networks:
  #- ssid: !secret wifi_ssid
  #  password: !secret wifi_password
  #  priority: 0.0
  - ssid: !secret wifi2_ssid
    password: !secret wifi2_password
  #  priority: 1.0
  #- ssid: !secret wifi3_ssid
  #  password: !secret wifi3_password
  #  priority: 2.0

  ap:
    ssid: "EspHome-Loviz"
    password: "12345678"

web_server:
  port: 80
  version: 3

globals:
  - id: fail_count
    type: int
    initial_value: '0'

binary_sensor:
  - platform: template
    id: internet_status
    name: "Internet Status"

sensor:
  - platform: template
    id: internet_fail_count
    name: "Internet Fails Count"
    update_interval: never

interval:
  - interval: 120s
    then:
      - http_request.get:
          url: !secret url_test
          on_response:
            then:
              - lambda: |-
                  id(fail_count) = 0;
              - sensor.template.publish:
                  id: internet_fail_count
                  state: 0
              - binary_sensor.template.publish:
                  id: internet_status
                  state: true

          on_error:
            then:
              - http_request.get:
                  url: !secret url_test2
                  on_response:
                    then:
                      - lambda: |-
                          id(fail_count) = 0;
                      - sensor.template.publish:
                          id: internet_fail_count
                          state: 0
                      - binary_sensor.template.publish:
                          id: internet_status
                          state: true

                  on_error:
                    then:
                      - lambda: |-
                          id(fail_count)++;
                          if (id(fail_count) > 3) id(fail_count) = 3;
                      - sensor.template.publish:
                          id: internet_fail_count
                          state: !lambda 'return id(fail_count);'
                      - lambda: |-
                          if (id(fail_count) >= 3) {
                            id(internet_status).publish_state(false);
                          }

http_request:
  useragent: esphome-loviz-check
  verify_ssl: false